### ISSUE TITLE
Post Exec Scripts ?

### ISSUE THREAD

**Issue by jcnoir** [blacklabelops/rsnapshot#3]
Hi,
Thanks for this tool.
I would want to execute some post exec rsnapshot script (tar + encrypt + ftp).
Is there any way to configure this using your docker image ?

Thank you.

``` bash
# Specify the path to a script (and any optional arguments) to run right
# before rsnapshot syncs files
#
#cmd_preexec    /path/to/preexec/script

# Specify the path to a script (and any optional arguments) to run right
# after rsnapshot syncs files
#
#cmd_postexec /path/to/postexec/script
```

**Comment by blacklabelops** [comment]
You will have to extend the image:

```
FROM blacklabelops/rsnapshot
COPY your-docker-entrypoint.sh /usr/bin/rsnapshot.d/your-docker-entrypoint.sh
COPY your-post-command.sh /usr/bin/rsnapshot.d/your-post-command.sh
ENTRYPOINT ["/usr/bin/cron.d/your-docker-entrypoint.sh"]
VOLUME ["${VOLUME_DIRECTORY}"]
CMD ["rsnapshot"]
```

Then your your-docker-entrypoint.sh:

```
#!/bin/bash

source /usr/bin/rsnapshot.d/rsnapshot.sh
echo -e cmd_postexec'\t'/usr/bin/rsnapshot.d/your-post-command.sh >> /etc/rsnapshot.conf

if [ "$1" = 'rsnapshot' ]; then
  exec rsnapshot $backup_interval
fi

exec "$@"
```

Hope this helps!

**Comment by jcnoir** [comment]
Thank you very much for your help.
I followed your instructions but I cannot get rsnapshot launch the postexec script. No error, the backup was done  but the postexec script was not launched.
I eventually built a custom Docker image based on Alpine that runs a custom backup script from crond.
